### ISSUE TITLE
Zurücksetzung/Deinstallation der App löscht Daten nicht korrekt.

### ISSUE THREAD

**Issue by lukitheflusspferd** [AntonioAlbt/kepler_app#20]
**Fehlerbeschreibung**
Ich wollte eigentlich einen anderen Bug(anscheinend #21) reproduzieren und musste dafür die App zurücksetzen(Einstellungen --> "Abmelden und neu Anmelden". Ein erneutes Anmelden schlug fehl; die App behauptete, ich sei noch angemeldet. Da ich mich wieder anmelden wollte, deinstallierte ich die App. Nach erneuter Installation trat die Fehlermeldung immer noch auf. Ich benutzte die Funktion, die App ohne Anmeldedaten zu benutzen, und meldete mich in den Einstellungen erneut ab. Im darauf folgenden Anmeldebildschirm funktionierte alles normal. --> #21 folgte darauf, in welchen wiederum dieser Fehler auftrat(bei Betätigung des angebotenen "Jetzt anmelden"-Button), Ein erneutes Zurücksetzen der App funktionierte.

**Schritte zum Reproduzieren**
Eine funktionierende App zurücksetzen
Mithilfe von #21 ebenfalls reproduzierbar.

**Dein Gerät**
 - Gerät: iPad Air (5. Gen)
 - Betriebssystem mit Version: iPadOS 18.0
 - App-Version: 2.6.1 (67)
 - App-Ursprung: App-Store

**Log-Ausschnitt**
Log erstellt: 02.10.2024 11:15
[02.10.2024 11:15] [I] (startup) --- LOG INIT ---
[02.10.2024 11:18] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:18] [D] (cal-data) loaded 1 events from https://www.kepler-chemnitz.de/wp-json/tribe/events/v1/events?start_date=2024-10-01&end_date=2024-10-31
[02.10.2024 11:18] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:18] [D] (cal-data) loaded 1 events from https://www.kepler-chemnitz.de/wp-json/tribe/events/v1/events?start_date=2024-10-01&end_date=2024-10-31
[02.10.2024 11:18] [D] (ls-api-call) called login, logout
[02.10.2024 11:18] [D] (ls-api-call) called login, set_focus, register_master, logout
[02.10.2024 11:18] [D] (ls-api-call) called get_nonce
[02.10.2024 11:18] [D] (ls-api-call) called login, set_options, get_information
[02.10.2024 11:18] [D] (ls-api-call) called set_session, reload
[02.10.2024 11:18] [D] (ls-api-call) called set_session, set_focus, get_entries
[02.10.2024 11:18] [D] (ls-api-call) called set_session, set_focus, get_entries
[02.10.2024 11:18] [D] (ls-api-call) called set_session, set_focus, get_file
[02.10.2024 11:18] [D] (ls-api-call) called set_session, reload
[02.10.2024 11:20] [D] (indiware) fetching https://plan.kepler-chemnitz.de/stuplanindiware/VmobilS/mobdaten/Klassen.xml
[02.10.2024 11:20] [D] (indiware) fetching https://plan.kepler-chemnitz.de/stuplanindiware/VmobilS/mobdaten/Klassen.xml
02.xml
[02.10.2024 11:20] [D] (indiware) fetching https://plan.kepler-chemnitz.de/stuplanindiware/VmobilS/mobdaten/PlanKl20241002.xml
[02.10.2024 11:20] [E] (indiware) HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)):
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
#3      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:923)
<asynchronous suspension>
#4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
<asynchronous suspension>

[02.10.2024 11:21] [D] (indiware) fetching https://plan.kepler-chemnitz.de/stuplanindiware/VmobilS/mobdaten/PlanKl20241002.xml
[02.10.2024 11:21] [D] (indiware) fetching https://plan.kepler-chemnitz.de/stuplanindiware/VmobilS/mobdaten/PlanKl20241002.xml
[02.10.2024 11:21] [D] (ls-api-call) called get_nonce
[02.10.2024 11:21] [D] (ls-api-call) called login, set_focus, unregister_master
[02.10.2024 11:21] [E] (platform-dispatcher-error) Null check operator used on a null value:
#0      _HomeLSTasksWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_tasks_home.dart:145)
#1      _HomeLSTasksWidgetState.initState (package:kepler_app/tabs/home/widgets/ls_tasks_home.dart:130)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5593)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6900)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4468)
#8      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7035)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3963)
#10     Element.updateChildren (package:flutter/src/widgets/framework.dart:4150)
#11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7060)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3941)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#15     BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693)
#16     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#23     _invoke (dart:ui/hooks.dart:312)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#25     _drawFrame (dart:ui/hooks.dart:283)

3)

[02.10.2024 11:21] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:21] [D] (cal-data) loaded 1 events from https://www.kepler-chemnitz.de/wp-json/tribe/events/v1/events?start_date=2024-10-01&end_date=2024-10-31
[02.10.2024 11:21] [D] (ls-api-call) called login, logout
[02.10.2024 11:21] [D] (ls-api-call) called login, set_focus, register_master, logout
[02.10.2024 11:21] [D] (ls-api-call) called set_session, set_focus, get_messages
null value:
#0      _HomeLSTasksWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_tasks_home.dart:145)
#1      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437)
#2      CredentialStore._setSaveNotify (package:kepler_app/libs/state.dart:70)
#3      CredentialStore.lernSaxLogin= (package:kepler_app/libs/state.dart:77)
#4      lernSaxLoginScreenMainProcessing (package:kepler_app/introduction.dart:69)
#5      _LernSaxScreenMainState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:kepler_app/introduction.dart:369)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861)
#7      Future._propagateToListeners (dart:async/future_impl.dart:890)
#8      Future._completeWithValue (dart:async/future_impl.dart:666)
<asynchronous suspension>

[02.10.2024 11:21] [E] (platform-dispatcher-error) Null check operator used on a null value:
#0      _HomeLSNotifsWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_notifs_home.dart:144)
#1      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437)
#2      CredentialStore._setSaveNotify (package:kepler_app/libs/state.dart:70)
#3      CredentialStore.lernSaxLogin= (package:kepler_app/libs/state.dart:77)
#4      lernSaxLoginScreenMainProcessing (package:kepler_app/introduction.dart:69)
#5      _LernSaxScreenMainState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:kepler_app/introduction.dart:369)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:861)
#7      Future._propagateToListeners (dart:async/future_impl.dart:890)
#8      Future._completeWithValue (dart:async/future_impl.dart:666)
<asynchronous suspension>

[02.10.2024 11:21] [D] (ls-api-call) called set_session, reload
[02.10.2024 11:21] [E] (lernsax) type 'Null' is not a subtype of type 'List<dynamic>' in type cast:
#0      getTasks (package:kepler_app/libs/lernsax.dart:390)
<asynchronous suspension>
#1      _HomeLSTasksWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_tasks_home.dart:145)
<asynchronous suspension>

pension>

[02.10.2024 11:22] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:22] [D] (pendel) fetched pendel data from https://pendel.vlant.de/logging
[02.10.2024 11:22] [D] (cal-data) loaded 1 events from https://www.kepler-chemnitz.de/wp-json/tribe/events/v1/events?start_date=2024-10-01&end_date=2024-10-31
[02.10.2024 11:22] [E] (indiware) HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)):
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
#3      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:923)
<asynchronous suspension>
#4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
<asynchronous suspension>

[02.10.2024 11:23] [E] (indiware) HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: application verification failure(handshake.cc:393)):
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:143)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:920)
#3      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:923)
<asynchronous suspension>
#4      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1049)
<asynchronous suspension>

[02.10.2024 11:23] [D] (ls-api-call) called set_session, reload
us, get_entries

[02.10.2024 11:23] [E] (lernsax) type 'Null' is not a subtype of type 'List<dynamic>' in type cast:
#0      getNotifications (package:kepler_app/libs/lernsax.dart:350)
<asynchronous suspension>
#1      _HomeLSNotifsWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_notifs_home.dart:144)
<asynchronous suspension>

[02.10.2024 11:23] [E] (lernsax) type 'Null' is not a subtype of type 'List<dynamic>' in type cast:
#0      getTasks (package:kepler_app/libs/lernsax.dart:390)
<asynchronous suspension>
#1      _HomeLSTasksWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_tasks_home.dart:145)
<asynchronous suspension>

[02.10.2024 11:23] [E] (lernsax) type 'Null' is not a subtype of type 'List<dynamic>' in type cast:
#0      getNotifications (package:kepler_app/libs/lernsax.dart:350)
<asynchronous suspension>
#1      _HomeLSNotifsWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_notifs_home.dart:144)
<asynchronous suspension>

[02.10.2024 11:23] [E] (lernsax) type 'Null' is not a subtype of type 'List<dynamic>' in type cast:
#0      getTasks (package:kepler_app/libs/lernsax.dart:390)
<asynchronous suspension>
#1      _HomeLSTasksWidgetState.loadData (package:kepler_app/tabs/home/widgets/ls_tasks_home.dart:145)
<asynchronous suspension>

**Comment by AntonioAlbt** [comment]
Hängt höchstwahrscheinlich auch mit Proxy-Fehlern zusammen - und damit, dass die App anscheinend mit den Fehlern an den Stellen im Log nicht richtig umgehen kann.
Muss ich mir mal genauer anschauen - hab nur halt jetzt weniger Zeit, bin jetzt am Studieren.

**Comment by lukitheflusspferd** [comment]
Dieser Fehler ist über mobile Daten passiert (wie auch #21). Gibt es dort auch Proxy?

**Comment by AntonioAlbt** [comment]
Ne, das wäre nur auf ein Schul-iPad zugetroffen. Auf dem normalen Gerät ist es trotzdem komisch, aber würde einen anderen Fehler erklären, den es speziell (eigentlich) nur mit iOS-Geräten gab. Wahrscheinlich sorgt bei iOS ein Zertifikatsfehler für eine Exception, wo das bei Android nicht der Fall sein wird. Ich hab CERTIFICATE_VERIFY_FAILED nämlich noch nie gesehen - aber gleichzeitig verstehe ich nicht, wieso bei der Webseite ein Zertifikatsfehler auftreten sollte.

**Comment by AntonioAlbt** [comment]
Verstehe ich das hier richtig, dass du die App erst zurückgesetzt hast, dann die neue Anmeldung nicht ging und du dann die App deinstalliert hast? Und nachdem du die App wieder installiert hast, war der Fehler immer noch?
D.h. irgendwie waren nach dem Neuinstallieren noch App-Daten da?

**Comment by AntonioAlbt** [comment]
Mir ist es auch nicht möglich, den Fehler zu reproduzieren - wenn ich auf "Abmelden und neu anmelden" gehe, komme ich auf den Anmeldebildschirm, auch nach Neustart der App.
Auch aus deinem Log geht hervor, dass zumindest die LernSax-Anmeldedaten gelöscht wurden - deshalb die Fehler mit `(lernsax) type 'Null' is not a subtype of type 'List' in type cast` für die Widgets.

Ergänzung: Ich habe es auch nochmal auf einem iPhone ausprobiert, auch dort ist der Fehler nicht aufgetreten.

**Comment by lukitheflusspferd** [comment]
So war es, @AntonioAlbt

**Comment by AntonioAlbt** [comment]
Ich hab gelesen, dass auf iOS Daten in der Keychain beim Deinstallieren nicht gelöscht werden, und die App speichert die Login-Daten dort. (siehe [Reddit](https://www.reddit.com/r/privacy/comments/lee6b8/fyi_ios_is_not_deleting_app_data_even_if_you/))
Die App muss also irgendwie die Daten beim ersten Start löschen.
